create extension if not exists pg_trgm;

create table sport_types (
  id bigint primary key generated by default as identity,
  name text not null unique
);

create table events (
  id bigint primary key generated by default as identity,
  name text not null,
  starts_at timestamptz not null,
  description text,
  created_by uuid not null references auth.users(id),

  -- Controlled list + free-form hybrid
  -- - if user selects from list: set both
  -- - if user free-forms: set sport_type_text, leave sport_type_id null
  sport_type_id bigint references sport_types(id),
  sport_type_text text not null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table event_venues (
  id bigint primary key generated by default as identity,
  event_id bigint not null references events(id) on delete cascade,
  name text not null,
  address_text text not null,
  details text
);

-- indexes

create index events_name_trgm_idx on events using gin (name gin_trgm_ops);

create index events_sport_type_id_idx on events (sport_type_id);

create index events_sport_starts_at_idx on events (sport_type_id, starts_at DESC);

create index event_venues_event_id_idx on event_venues (event_id);
